CREATE TABLE `block` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `miner` varchar(100) DEFAULT '',
  `hash` varchar(100) DEFAULT '',
  `number` varchar(100) DEFAULT '',
  `difficulty` varchar(100) DEFAULT '',
  `extra_data` varchar(100) DEFAULT '',
  `gas_limit` varchar(100) DEFAULT '',
  `gas_used` varchar(100) DEFAULT '',
  `mix_hash` varchar(100) DEFAULT '',
  `nonce` varchar(100) DEFAULT '',
  `number_int` varchar(100) DEFAULT '',
  `parent_hash` varchar(100) DEFAULT '',
  `receipts_root` varchar(100) DEFAULT '',
  `sha_3_uncles` varchar(100) DEFAULT '',
  `size` varchar(100) DEFAULT '',
  `state_root` varchar(100) DEFAULT '',
  `timestamp` varchar(100) DEFAULT '',
  `total_difficulty` varchar(100) DEFAULT '',
  `transactions_root` varchar(100) DEFAULT '',
  `created_on` int(10) unsigned DEFAULT '0' COMMENT '创建时间',
  `created_by` varchar(100) DEFAULT '' COMMENT '创建人',
  `modified_on` int(10) unsigned DEFAULT '0' COMMENT '修改时间',
  `modified_by` varchar(100) DEFAULT '' COMMENT '修改人',
  `deleted_on` int(10) unsigned DEFAULT '0',
  `state` tinyint(3) unsigned DEFAULT '1' COMMENT '状态 0为禁用、1为启用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文章标签管理';